name: CI/CD Workflow

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  ci:
    name: CI/CD Pipeline
    runs-on: ubuntu-latest

    env:
      PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
      PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
      PACTICIPANT: pactflow-provider
      OAS_PATH: oas/swagger.yml
      REPORT_PATH: report.txt
      REPORT_FILE_CONTENT_TYPE: text/plain
      VERIFIER_TOOL: restassured

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Determine the branch name
      - name: Set Branch Name
        id: set_branch_name
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      # Run tests and generate verification results
      - name: Run Tests
        run: |
          ./gradlew clean test > $REPORT_PATH || exit 1

      # Publish provider contract
      - name: Publish Provider Contract
        run: |
          docker run --rm -v $PWD:$PWD -w $PWD \
            -e PACT_BROKER_BASE_URL=$PACT_BROKER_BASE_URL \
            -e PACT_BROKER_TOKEN=$PACT_BROKER_TOKEN \
            pactfoundation/pact-cli:latest pactflow publish-provider-contract \
            $OAS_PATH \
            --provider $PACTICIPANT \
            --provider-app-version $(git rev-parse --short HEAD) \
            --branch $BRANCH_NAME \
            --content-type application/yaml \
            --verification-exit-code=0 \
            --verification-results $REPORT_PATH \
            --verification-results-content-type $REPORT_FILE_CONTENT_TYPE \
            --verifier $VERIFIER_TOOL || exit 1

      # Check if the provider can be deployed
      - name: Can I Deploy?
        id: can_i_deploy
        run: |
          docker run --rm -v $PWD:$PWD -w $PWD \
            -e PACT_BROKER_BASE_URL=$PACT_BROKER_BASE_URL \
            -e PACT_BROKER_TOKEN=$PACT_BROKER_TOKEN \
            pactfoundation/pact-cli:latest pact-broker can-i-deploy \
            --pacticipant $PACTICIPANT \
            --version $(git rev-parse --short HEAD) \
            --to-environment production \
            --retry-while-unknown 6 \
            --retry-interval 10 || exit 1

      # Record deployment in PactFlow
      - name: Record Deployment
        run: |
          docker run --rm -v $PWD:$PWD -w $PWD \
            -e PACT_BROKER_BASE_URL=$PACT_BROKER_BASE_URL \
            -e PACT_BROKER_TOKEN=$PACT_BROKER_TOKEN \
            pactfoundation/pact-cli:latest pact-broker record-deployment \
            --pacticipant $PACTICIPANT \
            --version $(git rev-parse --short HEAD) \
            --environment production || exit 1